version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/my-app
    stdin_open: true
    tty: true
  npm_next_js:
    image: node
    working_dir: /my-app
    volumes:
      - ./:/my-app
  npm_packages:
    image: node
    working_dir: /my-app
    command: npm install
    volumes:
      - ./:/my-app
